### ISSUE TITLE
 Use enums where appropriate

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/fastcs-eiger#43]
From a client perspective it is nice when there are only a select number of values that a PV could have to be able to use an enum i.e. a `bo`/`mbbo`. Examples so far:

* `BitDepthReadout`
* `DetectorState`
* `RoiMode`
* `TriggerMode`

## Acceptance Criteria
- PVs above are `mbbo`/`mbbi`s with appropriate options

**Comment by GDYendell** [comment]
This is possible via https://github.com/DiamondLightSource/FastCS/pull/40
